#ifndef CONSTANT_S
#define CONSTANT_S

#define WINDOW_X 1920
#define WINDOW_Y 1080


// HP CONSTANTS
#define SHIP_HP 10
#define ENEYMY_SHIP_HP 7

// SHAPE CONSTANTS
#define SPACE_SHIP 1
#define ENEMY_SHIP 2 
#define SENTRY 3

// SIZE CONSTANTS
#define SPACE_SHIP_WIDTH 10
#define SPACE_SHIP_HEIGHT 10

#endif